# Autogenerated wrapper script for libstrophe_jll for aarch64-apple-darwin
export libstrophe

using Expat_jll
using OpenSSL_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libstrophe")
JLLWrappers.@declare_library_product(libstrophe, "@rpath/libstrophe.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, OpenSSL_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libstrophe,
        "lib/libstrophe.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
